name: Daily Job Scrape

on:
  schedule:
    - cron: '0 18 * * *' # Runs daily at 8:00 AM HST (18:00 UTC)
  workflow_dispatch: # Allows you to run it manually for testing

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add jobs.json
          git commit -m "Updated job listings" || exit 0
          git push
